export const fakultas = [
  "FAPET",
  "FEB",
  "FH",
  "FIB",
  "FIA",
  "FILKOM",
  "FISIP",
  "FK",
  "FKG",
  "FKH",
  "FMIPA",
  "FP",
  "FPIK",
  "FT",
  "FTP",
  "VOKASI",
]

export const coreTeam = {
  organizer: [
    {
      nama: "Paloga Treheya Munthaha",
      email: "palogatreheya@gmail.com",
      linkedin: "palogatreheya",
      instagram: "@misterlogaloga",
      divisi: "Organizer",
      foto: "Paloga.jpg",
    },
    {
      nama: "Aurora Rivera Maulidina",
      email: "aurorarivera@student.ub.ac.id",
      linkedin: "aurora-rivera-maulidina-1967a0190",
      instagram: "@rivera.au",
      divisi: "Co-Organizer",
      foto: "AuroraRivera.jpeg",
    },
  ],
  curator: [
    {
      nama: "Siti Huwaena Maulidiah",
      email: "gadisaa29@gmail.com",
      linkedin: "",
      instagram: "@gadisamaulidiah",
      divisi: "Curator",
      foto: "gadisamaulidiah.jpeg",
    },
    {
      nama: "Insky Johana Sheren Rottie",
      email: "shereninsky@gmail.com",
      linkedin: "inskyjohana",
      instagram: "@inskyjo",
      divisi: "Curator",
      foto: "InskyJohanaSherenRottie.jpeg",
    },
    {
      nama: "Rafly Al Mahdy",
      email: "raflyalmahdy1@gmail.com",
      linkedin: "rafly-mahdy",
      instagram: "@102rafly",
      divisi: "Curator",
      foto: "RaflyAlMahdy.jpg",
    },
  ],
  budgetManager: [
    {
      nama: "Hamzah Abdul Jabbar",
      email: "hamzah0921@gmail.com",
      linkedin: "hamzahabduljabbar",
      instagram: "@hamzahoods",
      divisi: "Budget Manager",
      foto: "Hamzah.jpeg",
    },
    {
      nama: "Sophia Aviana Adiningtyas",
      email: "Sophiaavn@gmail.com",
      linkedin: "",
      instagram: "@Sophiaaviana",
      divisi: "Budget Manager",
      foto: "SophiaAvianaAdiningtyas.jpeg",
    },
  ],
  sponsorship: [
    {
      nama: "Nadiyah Farakh Putri",
      email: "nadiyahfp8@gmail.com",
      linkedin: "",
      instagram: "@nadiaafp",
      divisi: "Sponsorship",
      foto: "NadiyahFarakh.jpeg",
    },
    {
      nama: "Alvin Ilham Hanafi",
      email: "alvinhanafiii@gmail.com",
      linkedin: "alvinilhamhanafi",
      instagram: "@alvinhnfi",
      divisi: "Sponsorship",
      foto: "AlvinIlhamHanafi.jpg",
    },
  ],
  eventManager: [
    {
      nama: "M. Ilham Haikal Jogo Fauzi Baqy",
      email: "jogofauzi@gmail.com",
      linkedin: "jogo-fauzi-b69673201",
      instagram: "@jog.o",
      divisi: "Event Manager",
      foto: "MIlhamHaikalJogoFauziBaqy.jpeg",
    },
    {
      nama: "Nabita Sadira Putri Ichwani",
      email: "bitasadira@gmail.com",
      linkedin: "nabita-sadira-a5b4761b3",
      instagram: "@bitasadira",
      divisi: "Event Manager",
      foto: "NabitaSadira.jpeg",
    },
  ],
  executiveProducer: [
    {
      nama: "Cindy Putri Nursanthyasto",
      email: "cindynursanthyasto@gmail.com",
      linkedin: "cindy-nursanthyasto",
      instagram: "@cindypn15",
      divisi: "Executive Producer",
      foto: "CindyNursanthyasto.jpeg",
    },
    {
      nama: "Siti Almira Shakilla",
      email: "workwith.almira@gmail.com",
      linkedin: "",
      instagram: "@kkomurolla",
      divisi: "Executive Producer",
      foto: "AlmiraShakilla.png",
    },
  ],
  cem: [
    {
      nama: "Sekar Heksagara Tanjung",
      email: "sekar.heksagara01@gmail.com",
      linkedin: "sekarheksagaratanjung",
      instagram: "@sekarheksagara",
      divisi: "CEM",
      foto: "SekarHeksagara.jpg",
    },
    {
      nama: "Davina Alya Shakira",
      email: "davinasoemardi@gmail.com",
      linkedin: "",
      instagram: "@davinaalya",
      divisi: "CEM",
      foto: "DavinaShakira.png",
    },
  ],
  designer: [
    {
      nama: "Gegana Bintang Dewa Pratama",
      email: "gana.bdp16@gmail.com",
      linkedin: "",
      instagram: "@g.gana_",
      divisi: "Designer",
      foto: "GanaBintang.jpeg",
    },
    {
      nama: "Ilham Firdaus",
      email: "ilhamfrds567@gmail.com",
      linkedin: "",
      instagram: "@ilham_frds",
      divisi: "Designer",
      foto: "IlhamFirdaus.jpg",
    },
  ],
  videoProduction: [
    {
      nama: "Adani Zata Yumni",
      email: "adanizatayumni@gmail.com",
      linkedin: "adanizata",
      instagram: "@adanizata_",
      divisi: "Video Production",
      foto: "AdaniZataYumni.jpg",
    },
    {
      nama: "Egananda Kurniawan",
      email: "kegananda@gmail.com",
      linkedin: "egananda",
      instagram: "@egananda_k",
      divisi: "Video Production",
      foto: "EganandaKurniawan.png",
    },
  ],
  websiteManager: [
    {
      nama: "Muhammad Arga Farrel Arkaan",
      email: "argafrl5@gmail.com",
      linkedin: "muhammad-arga",
      instagram: "@argafrl",
      divisi: "Website Manager",
      foto: "MuhammadArga.jpg",
    },
    {
      nama: "Randy Christian Saputra",
      email: "randyputra451@gmail.com",
      linkedin: "randyptr",
      instagram: "@randychrist_",
      divisi: "Website Manager",
      foto: "RandyChristianSaputra.png",
    },
  ]
}

export const volunteer = {
  curator: [
    "M. FAQIH RABBANI ALHAVIDZI",
    "ELSHADDAI HOSANNA PRASETYO",
    "LUTHFIA FAHIRA",
    "PRICILLA PHILIA BR. PURBA",
  ],
  sponsorship: [
    "AHMAD NUR DZAKY",
    "RASYANDA AZKAMADIRA SIREGAR",
    "M. CHOIRUL ANAM ANCAH",
    "AILEEN MAYDA DWINA",
    "DINA FAJRIATI",
  ],
  eventManager:[
    "GAIZKA RIFAT MUZAKKI",
    "AMIRA NADA FAUZIYYAH",
    "ABYGAIL ZHOFIANA",
    "FADHIL MUHAMMAD",
    "ALOYSIUS ARDEYNO",
    "DELISTRIA AISYAH NUR",
  ],
  executiveProducer:[
    "KAYLA KAMILA SUPRAPTO PUTRI",
    "AIRLANGGA PUTRA KUSUMO",
    "SHALHAN HIRZI",
    "MUHAMMAD SURYA SIDDIQ",
    "MAULANA SHAFARIYANTO",
    "MUHAMMAD ZULKIFLI NAWFAL",
  ],
  cem:[
    "ANANDA PUTRI",
    "AZZAHRA MAYRAINA",
    "TSANI ADAM ZIDAN ABIDIN",
    "NADIA AZZAHRA INAS",
  ],
  designer:[
    "DAFFA RAMADANI",
    "YASMIN BAHARMUS",
    "BERNADETA RINDA",
    "SABRINA MUJAHDILA TASHDIQA",
  ],
  videoProduction:[
    "MARTINUS TEJAKUSUMA",
    "MUHAMMAD FERDIAN SUSANTO",
    "AQSA RADITYA BINTANG JULIANO",
    "NABYL FADHLURRAHMAN",
  ],
  website:[
    "ALFONSUS AVIANTO CHANDRAWAN",
    "ADITYA RIZKY RAMADHAN",
    "LUVITA INTAN CAHYANI",
    "MIFTAHUL IHSAN",
  ],
};